### ISSUE TITLE
Possible typo error in the data.py

### ISSUE THREAD

**Issue by ZHG2017** [leonard-seydoux/scatnet#2]
The original file at line 17 has the following module importation:
```python
from sklearn.feature_extraction.image import extract_patches as buff
```
which will raise the runtime error as follows:
> ImportError: cannot import name 'extract_patches' from 'sklearn.feature_extraction.image' (/home/zhg/MIAM/.scatnet/lib/python3.8/site-packages/sklearn/feature_extraction/image.py)
> Searching in the documentation of sklearn(c.f. https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.image.extract_patches_2d.html), 

I think it should be replaced with the following module importation:
```python
from sklearn.feature_extraction.image import extract_patches_2d as buff
```
However another problem arose as follows:
> TypeError: extract_patches_2d() got an unexpected keyword argument 'patch_shape'

**Comment by wgajek** [comment]
I thought the same but got stuck at the same place as you. Ultimately it's not a type but currently extract_patches (no 2d) is missing in sklearn (I guess it was there before).

Found it somewhere else https://gemfury.com/stream/python:scikit-learn/-/content/feature_extraction/image.py and added required imports. You can import it to main.py using e.g.  from extract_patches_my import extract_patches as buff

`def extract_patches(arr, patch_shape=8, extraction_step=1):
    import numbers
    import numpy as np
    from numpy.lib.stride_tricks import as_strided
    """Extracts patches of any n-dimensional array in place using strides.

    Given an n-dimensional array it will return a 2n-dimensional array with
    the first n dimensions indexing patch position and the last n indexing
    the patch content. This operation is immediate (O(1)). A reshape
    performed on the first n dimensions will cause numpy to copy data, leading
    to a list of extracted patches.

    Read more in the :ref:`User Guide <image_feature_extraction>`.

    Parameters
    ----------
    arr : ndarray
        n-dimensional array of which patches are to be extracted

    patch_shape : integer or tuple of length arr.ndim
        Indicates the shape of the patches to be extracted. If an
        integer is given, the shape will be a hypercube of
        sidelength given by its value.

    extraction_step : integer or tuple of length arr.ndim
        Indicates step size at which extraction shall be performed.
        If integer is given, then the step is uniform in all dimensions.


    Returns
    -------
    patches : strided ndarray
        2n-dimensional array indexing patches on first n dimensions and
        containing patches on the last n dimensions. These dimensions
        are fake, but this way no data is copied. A simple reshape invokes
        a copying operation to obtain a list of patches:
        result.reshape([-1] + list(patch_shape))
    """

    arr_ndim = arr.ndim

    if isinstance(patch_shape, numbers.Number):
        patch_shape = tuple([patch_shape] * arr_ndim)
    if isinstance(extraction_step, numbers.Number):
        extraction_step = tuple([extraction_step] * arr_ndim)

    patch_strides = arr.strides

    slices = [slice(None, None, st) for st in extraction_step]
    indexing_strides = arr[slices].strides

    patch_indices_shape = ((np.array(arr.shape) - np.array(patch_shape)) //
                           np.array(extraction_step)) + 1

    shape = tuple(list(patch_indices_shape) + list(patch_shape))
    strides = tuple(list(indexing_strides) + list(patch_strides))

    patches = as_strided(arr, shape=shape, strides=strides)
    return patches`


Also to make it work data is necessar and it's lacking. You can use:
from obspy.clients.fdsn import Client
client = Client("IRIS")
from obspy import UTCDateTime
t1=UTCDateTime("20170617T12:00:00")
t2=UTCDateTime("20170617T23:59:00")
st = client.get_waveforms("CI","LRL","*","HHZ",t1,t2)
st.write("CI.LRL..HHZ", format="MSEED")

to get proper file with data

this code a large number of bugs (currently - maybe versioning changed). It would be helpful to specify required versions of packages

**Comment by leonard-seydoux** [comment]
Hello, sorry for the very late reply. If was out of this project after the deprecation with TensorFlow1.x and didn't get notified since then. I decided to implement a new version since then, available at https://scatseisnet.readthedocs.io. I hope this new version will help better since we planned to maintain it much more. I see in the other issues of the scatnet repository that some people worked on a TensorFlow 2.x version, FYI. 

For now I'm closing all the issues since the code is not maintained anymore (see the updated README) but will reopen maybe one day if we can merge the improvements made with those persons.
